name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: # Allows you to run this workflow manually
    inputs:
      customKey:
        description: "Custom thing"
        required: true
        default: "MY_VALUE_123"
  
env:
  VAR1: false
  TMP_VAR: ""
  VAR_TEST: test-${{github.event.inputs.customKey}}
  VAR_IN1: ${{github.event.inputs.customKey || 'fallback2'}}
  VERSIONS_TO_KEEP: 3

jobs:
  Build:
    name: "Build stuff 🔨"
    runs-on: ubuntu-latest
    
    env:
      VAR2: false
      FALLBACK: "stringue"
      VAR_IN2: ${{github.event.inputs.customKey || 'fallback2'}}

    # Steps represent a sequence of tasks that will be executed
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          
      - run: OUTPUT=${TMP_VAR:-FALLBACK}
        
      - run: echo $OUTPUT

      - name: PWD
        run: pwd

      - name: PRINT VARIABLES
        env:
          VAR3: "Hello ${{env.VAR1}}"
        run: echo $VAR1 $VAR2 $VAR3 $VAR_IN1 $VAR_IN2

      - name: Test conditional 1
        if: ${{ env.VAR1 == true }}
        run: echo "It ran 🏃‍☹️"

      - name: Test conditional 2
        if: ${{ env.VAR2 == true }}
        run: echo "It ran 🏃‍☹️"

      - name: Print env
        run: env

      - name: Perform bash calc
        run: echo $(($GITHUB_RUN_NUMBER - $VERSIONS_TO_KEEP))

      - name: Print stuff
        run: |
          pwd
          echo $RUNNER_WORKSPACE
          echo $GITHUB_WORKSPACE

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  Build2:
    if: ${{ false }}
    name: "Build v2"
    runs-on: ubuntu-latest

    steps:
      - run: echo "it ran"

