name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: # Allows you to run this workflow manually
  
env:
  VAR1: test1
  VERSIONS_TO_KEEP: 3

jobs:
  build-job:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Test
        run: echo $VAR1 $VAR2

      - name: Print env
        run: env
        
      - name: Perform bash calc
        run: echo $(($GITHUB_RUN_NUMBER - $VERSIONS_TO_KEEP))
        
      - name: Print stuff
        run: |
          pwd
          echo $RUNNER_WORKSPACE
          echo $GITHUB_WORKSPACE

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
