name: Merge

on:
  push:
    branches: [master]

concurrency:
  group: merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tag:
    name: Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: tag
        run: |
          VERSION=v${{ github.run_number }}
          echo "Tagging $VERSION"
          git tag -a $VERSION -m "Tag $VERSION"
          git push $VERSION
