name: Reusable

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to run on"
        type: choice
        options: [master, next, dev]
        required: true
        default: "master"
      param:
        description: "Custom thing"
        type: string
        required: false

jobs:
  test:
    name: Test 👀
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    steps:
      - name: PWD
        run: pwd

      - run: echo "PARAM_VAR=1234" >> $GITHUB_ENV

      - run: echo $PARAM_VAR

      - name: Print env
        run: env

      - name: Perform bash calc
        run: echo $(($GITHUB_RUN_NUMBER - $PARAM_VAR))

      - name: Print stuff
        run: |
          pwd
          echo $RUNNER_WORKSPACE
          echo $GITHUB_WORKSPACE

      - name: Run if inputs.param == null
        if: ${{!inputs.param}}
        run: echo "inputs.param is undefined!"

      - name: Run if inputs.param == null
        if: ${{inputs.param}}
        run: echo "inputs.param defined ${{inputs.param}}"

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test2:
    if: ${{ false }}
    name: Test 2
    runs-on: ubuntu-latest

    steps:
      - run: echo "it ran"
